language: ruby

sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.2.4.1
  - jruby-head

before_install:
  - gem install bundler

script:
  - bundle exec rake test MONGO=1
  - bundle exec cucumber

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

cache: bundler

services:
  - mongodb
