language: ruby

sudo: false

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.7.0
  - jruby-head

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

cache: bundler

services:
  - mongodb
